### ISSUE TITLE
No module named 'psutil'

### ISSUE THREAD

**Issue by ochui** [SimFin/pdf-crawler#9]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxx/Documents/Github/wordbank/pdf-crawler/crawler/__init__.py", line 7, in <module>
    from crawler.handlers import (
  File "/home/xxxx/Documents/Github/wordbank/pdf-crawler/crawler/handlers.py", line 5, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'

**Comment by thf24** [comment]
I guess you just have to install it via pip install psutil
But it's missing in the requirements so I'll add it there
